name: hippo_env
channels: 
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - chromadb=0.4.24
  - langchain=0.1.17
  - llama-cpp-python=0.2.69
  - nltk=3.8.1
  - ollama=0.1.17
  - orjson=3.10.3
  - sentence-transformers=2.7.0
  - sentencepiece=0.2.0
  - wikipedia=1.4.0
  # dev
  - pandas
  - pytest=8.1.1
  - groq