name: hippo_env
channels: 
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - chromadb=0.4.24
  - langchain=0.1.11
  - ollama=0.1.17
  - orjson=3.9.15
  - sentence-transformers=2.5.1
  - wikipedia=1.4.0
  # dev
  - pandas
  - pytest=8.1.1
  - groq